local apply = require("../apply")

print("Run tests for `apply`")

apply(function(a, b)
  print("first argument is 1")
  assert(a == 1)
  print("second argument is 2")
  assert(b == 2)
end, 1, 2)

apply(function(a, b)
  print("array argument is unpacked")
  assert(a == 1)
  assert(b == 2)
end, {1, 2})

apply(function(a, b, c, d)
  print("last array argument is unpacked")
  assert(a == 1)
  assert(b == 2)
  assert(c == 3)
  assert(d == 4)
end, 1, 2, {3, 4})

apply(function(a, b, c, d)
  print("last nil arguments is included")
  assert(a == 1)
  assert(b == nil)
  assert(c == 3)
  assert(d == 4)
end, 1, nil, {3, 4})

apply(function(a, b, c, d, e)
  print("nil arguments are not skipped")
  assert(a == 1)
  assert(b == nil)
  assert(c == 2)
  assert(d == 3)
  assert(e == 4)
end, 1, nil, 2, {3, 4})

apply(function(a, b, c, d, e, f)
  print("nil arguments in last array argument is not skipped")
  assert(a == 1)
  assert(b == nil)
  assert(c == 2)
  assert(d == 3)
  assert(e == nil)
  assert(f == 4)
end, 1, nil, 2, {3, nil, 4})

apply(function(a, b, c, d)
  print("first nil item in the last array argument is not skipped")
  assert(a == 1)
  assert(b == nil)
  assert(c == nil)
  assert(d == 2)
end, 1, nil, {nil, 2})

apply(function(a, b, c, d, e)
  print("last nil argument before array & 1st nil item was not skipped")
  assert(a == nil)
  assert(b == 1)
  assert(c == nil)
  assert(d == nil)
  assert(e == 2)
end, nil, 1, nil, {nil, 2})

